### ISSUE TITLE
Some question about interpretability of DrugBAN

### ISSUE THREAD

**Issue by ninjaxfy** [pz-white/DrugBAN#5]
Dear Doctor Bai:
**The work DrugBAN is definitely excellent work!** For it combines the domain adversarial network and interpretability, both essential problems in drug discovery. 
However, I can not understand completely when the target domain data are predicted if the interpretability module will work in the target domain Proteins and Drugs. 
For the output of attention module may be influenced by the CDAN.
(I do not know much of it maybe because of my reading of the preprint version of your paper neither the version in NMI).
Thanks for your reading my question again!

**Comment by peizhenbai** [comment]
Thank you for your interest. The attention module still works for the target domain as its mechanism is unchanged. However, since the target domain is for out-of-distribution prediction, its interpretability is naturally weaker than in-domain prediction data. DrugBAN is a data-driven method, so increasing the amount of training data can provide more interpretable insights.

**Comment by ninjaxfy** [comment]
Got it!! Thanks a lot!
